### ISSUE TITLE
Assignment question

### ISSUE THREAD

**Issue by Sophie724** [Sophie724/modularity-mindfulness#1]
Hi Christian/ Anna,

I have some question of the assignment.

1. Can you give me some guidance of how to make the heading 1 into two lines. 
2. I can't add margin around the a tag under the section > article. Can you take a look of it. 

Thank you:)
[modularity-mindfulness.zip](https://github.com/Sophie724/modularity-mindfulness/files/7271607/modularity-mindfulness.zip)

@thatkidmadrid @ anna-pokhilenko

**Comment by thatkidmadrid** [comment]
Hi Sophie, I wanted to confirm if you still need help with this. I did not get notified until today and I see that it's already closed

**Comment by thatkidmadrid** [comment]
1. I see you're using floats and other styling to achieve the 2-lines for the h1, but you can use flexbox to achieve a similar layout. 
2. Flexbox will also be a key to aligning the items inside of each of your articles. Using `margin-top: auto` will be handy to help align the links to the bottom too. Refer to the [CSS Layout Cheatsheet](https://learn-the-web.algonquindesign.ca/topics/css-layout-cheat-sheet/) to see what this does

**Comment by Sophie724** [comment]
Hi Christian
Thank you for your reply. I have already solved the problem. :)
